name: perturbation-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          sudo -H pip install torch==1.7.0 torchvision==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
          sudo -H pip install pillow
          python run_model_tests.py

          # Write your CML report
          cat results.txt >> report.md
          cml-send-comment report.md